### Code along, Pandas Serires

In [35]:
import pandas as pd

data = dict(AI=25, Net=30, Java=27, App=56)

series = pd.Series(data=data)

print(series)
print(f"series[0]: {series[0]}")
print(f"series[1]: {series[1]}")
print(f"Series keys: {series.keys()}")
print(f"Series keys: {series[series.keys()[0]]}")

print(f"Series by colum: {series["AI"]}")

AI      25
Net     30
Java    27
App     56
dtype: int64
series[0]: 25
series[1]: 30
Series keys: Index(['AI', 'Net', 'Java', 'App'], dtype='object')
Series keys: 25
Series by colum: 25

C:\Users\User\AppData\Local\Temp\ipykernel_9816\217487598.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"series[0]: {series[0]}")
C:\Users\User\AppData\Local\Temp\ipykernel_9816\217487598.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"series[1]: {series[1]}")

In [36]:
import random as rng

rng.seed(42)

dice_series = pd.Series([rng.randint(1, 6) for _ in range(500000)])

print(dice_series)

print(f"Min Value {dice_series.min()}")
print(f"Max Value {dice_series.max()}")
print(f"Mean Value {dice_series.mean()}")
print(f"Median Value {dice_series.median()}")
print(f"Standard Value {dice_series.std()}")

0         6
1         1
2         1
3         6
4         3
         ..
499995    4
499996    3
499997    6
499998    1
499999    4
Length: 500000, dtype: int64
Min Value 1
Max Value 6
Mean Value 3.501112
Median Value 4.0
Standard Value 1.7089050892806212

In [37]:
df = pd.DataFrame(series, columns=["Num students"])

print(df)
print(df.T)

      Num students
AI              25
Net             30
Java            27
App             56
              AI  Net  Java  App
Num students  25   30    27   56

In [39]:
students = pd.Series(data= dict(AI=25, Net=30, Java=27, App=56))

language = pd.Series(dict(AI="Python", Net="C#", App="Kotlin", Java="Java"))

df_programs = pd.DataFrame({"Students" : students, "Language": language})
df_programs

      Students Language
AI          25   Python
App         56   Kotlin
Java        27     Java
Net         30       C#

In [48]:
import numpy as np
# Data frame är en samling av series

df_programs = pd.DataFrame({
    "Students": np.array((25, 30, 30, 27)),
    "Language": np.array(("Python", "C#", "Kotlin", "Java"))},
    index = ["AI", "Net", "App", "Java"])
df_programs.index

df_programs["Language"]["Net"]

print(df_programs.loc["Java"])

df_programs.loc[["Java", "AI"]]

df_programs.iloc[1:3]

df_programs.loc[df_programs["Students"] > 28]

Students      27
Language    Java
Name: Java, dtype: object

     Students Language
Net        30       C#
App        30   Kotlin

df=df[conditions] # Conditons är ett boolsk uttryck, dvs sant eller falskt

In [49]:
df_programs

      Students Language
AI          25   Python
Net         30       C#
App         30   Kotlin
Java        27     Java

In [59]:
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("calories.xlsx")  
df.head()

,FoodCategory,FoodItem,per100grams,Cals_per100grams,KJ_per100grams
0,CannedFruit,Applesauce,100g,62 cal,260 kJ
1,CannedFruit,Canned Apricots,100g,48 cal,202 kJ
2,CannedFruit,Canned Blackberries,100g,92 cal,386 kJ
3,CannedFruit,Canned Blueberries,100g,88 cal,370 kJ
4,CannedFruit,Canned Cherries,100g,54 cal,227 kJ

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2225 entries, 0 to 2224
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FoodCategory      2225 non-null   object
 1   FoodItem          2225 non-null   object
 2   per100grams       2225 non-null   object
 3   Cals_per100grams  2225 non-null   object
 4   KJ_per100grams    2225 non-null   object
dtypes: object(5)
memory usage: 87.0+ KB

In [61]:
df["FoodCategory"].unique()

array(['CannedFruit', 'Fruits', 'Tropical&ExoticFruits', 'PotatoProducts',
       'Vegetables', 'FastFood', 'Pizza', 'Cheese', 'CreamCheese',
       'Milk&DairyProducts', 'SlicedCheese', 'Yogurt', 'Beef&Veal',
       'ColdCuts&LunchMeat', 'Meat', 'Offal&Giblets', 'Pork',
       'Poultry&Fowl', 'Sausage', 'Venison&Game', 'Cakes&Pies',
       'Candy&Sweets', 'IceCream', '(Fruit)Juices',
       'AlcoholicDrinks&Beverages', 'Beer',
       'Non-AlcoholicDrinks&Beverages', 'Soda&SoftDrinks', 'Wine',
       'CerealProducts', 'Oatmeal,Muesli&Cereals', 'Pasta&Noodles',
       'Dishes&Meals', 'Soups', 'Legumes', 'Nuts&Seeds', 'Oils&Fats',
       'VegetableOils', 'BakingIngredients', 'Fish&Seafood',
       'Herbs&Spices', 'Pastries,Breads&Rolls', 'Sauces&Dressings',
       'Spreads'], dtype=object)

In [62]:
df["per100grams"].unique()

array(['100g', '100ml'], dtype=object)

In [67]:
df =df.rename(dict(Cals_per100grams = "Calories",
                   per100grams = "precent",
                   KJ_per100grams = "kj"), axis= "columns")

df

     FoodCategory             FoodItem precent Calories       kj
0     CannedFruit           Applesauce    100g   62 cal   260 kJ
1     CannedFruit      Canned Apricots    100g   48 cal   202 kJ
2     CannedFruit  Canned Blackberries    100g   92 cal   386 kJ
3     CannedFruit   Canned Blueberries    100g   88 cal   370 kJ
4     CannedFruit      Canned Cherries    100g   54 cal   227 kJ
...           ...                  ...     ...      ...      ...
2220      Spreads     Sunflower Butter    100g  617 cal  2591 kJ
2221      Spreads             Tapenade    100g  233 cal   979 kJ
2222      Spreads      Unsalted Butter    100g  717 cal  3011 kJ
2223      Spreads             Vegemite    100g  180 cal   756 kJ
2224      Spreads           Wild Honey    100g  286 cal  1201 kJ

[2225 rows x 5 columns]

In [68]:
df["Calories"] = df["Calories"].str[:-3].astype(int)

df

     FoodCategory             FoodItem precent  Calories       kj
0     CannedFruit           Applesauce    100g        62   260 kJ
1     CannedFruit      Canned Apricots    100g        48   202 kJ
2     CannedFruit  Canned Blackberries    100g        92   386 kJ
3     CannedFruit   Canned Blueberries    100g        88   370 kJ
4     CannedFruit      Canned Cherries    100g        54   227 kJ
...           ...                  ...     ...       ...      ...
2220      Spreads     Sunflower Butter    100g       617  2591 kJ
2221      Spreads             Tapenade    100g       233   979 kJ
2222      Spreads      Unsalted Butter    100g       717  3011 kJ
2223      Spreads             Vegemite    100g       180   756 kJ
2224      Spreads           Wild Honey    100g       286  1201 kJ

[2225 rows x 5 columns]

In [70]:
solids = df[df["precent"] == "100g"]
solids.head()
solids.shape

(1802, 5)

In [71]:
solids_sorted = solids.sort_values(by="Calories", ascending=False)

solids_sorted.iloc[:5]

     FoodCategory     FoodItem precent  Calories       kj
1621        Soups      Goulash    100g      1009  4238 kJ
528     Beef&Veal  Beef Tallow    100g       902  3788 kJ
1761    Oils&Fats         Lard    100g       902  3788 kJ
675          Pork         Lard    100g       898  3772 kJ
599          Meat  Chicken Fat    100g       898  3772 kJ

In [73]:
solids_sorted = solids.sort_values(by="FoodItem", ascending=True)

solids_sorted.iloc[:5]

               FoodCategory      FoodItem precent  Calories       kj
915            Candy&Sweets  3 Musketeers    100g       400  1680 kJ
29                   Fruits          Acai    100g        70   294 kJ
83    Tropical&ExoticFruits       Acerola    100g        32   134 kJ
1707             Nuts&Seeds         Acorn    100g       387  1625 kJ
476                  Yogurt       Activia    100g        74   311 kJ